const ShopActionTypes = {
  REQUEST_COLLECTIONS_START: "REQUEST_COLLECTIONS_START",
  REQUEST_COLLECTIONS_SUCCESS: "REQUEST_COLLECTIONS_SUCCESS",
  REQUEST_COLLECTIONS_ERROR: "REQUEST_COLLECTIONS_ERROR",
};

export default ShopActionTypes;
